// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw7ADLCGw8riQIIVI8A1iBeucGYengpv8',
    appId: '1:83858917951:web:f7c600f236f3a575c0068a',
    messagingSenderId: '83858917951',
    projectId: 'flutter-projects-2e525',
    authDomain: 'flutter-projects-2e525.firebaseapp.com',
    storageBucket: 'flutter-projects-2e525.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWuEe2aJ2sgeKHAN5jNsO9nJyXDCLOEK0',
    appId: '1:83858917951:android:1b784c69a8de8f96c0068a',
    messagingSenderId: '83858917951',
    projectId: 'flutter-projects-2e525',
    storageBucket: 'flutter-projects-2e525.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWD9YMtV5gwwoK5hl7aTdOC6Uuot7h404',
    appId: '1:83858917951:ios:78178a587c6b09f9c0068a',
    messagingSenderId: '83858917951',
    projectId: 'flutter-projects-2e525',
    storageBucket: 'flutter-projects-2e525.firebasestorage.app',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWD9YMtV5gwwoK5hl7aTdOC6Uuot7h404',
    appId: '1:83858917951:ios:78178a587c6b09f9c0068a',
    messagingSenderId: '83858917951',
    projectId: 'flutter-projects-2e525',
    storageBucket: 'flutter-projects-2e525.firebasestorage.app',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw7ADLCGw8riQIIVI8A1iBeucGYengpv8',
    appId: '1:83858917951:web:7c1cd9f94f62771dc0068a',
    messagingSenderId: '83858917951',
    projectId: 'flutter-projects-2e525',
    authDomain: 'flutter-projects-2e525.firebaseapp.com',
    storageBucket: 'flutter-projects-2e525.firebasestorage.app',
  );
}
